{{/* The rendered objects' name prefix. */}}
{{- define "observability-dashboards.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Every object's common labels: what it is, what release rendered it, and
the sidecar's own label so Grafana's dashboard sidecar collects it.
`grafana_dashboard: "1"` is the k8s-sidecar convention
charts/observability-stack's `grafana.sidecar.dashboards.label` sets.
*/}}
{{- define "observability-dashboards.labels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
grafana_dashboard: "1"
{{- end -}}

{{/*
The shipped catalog: name -> {folder, file}, generated by
hack/dashboards.sh into dashboards/catalog.yaml. Read here rather than
duplicated in this file so the two can never drift.
*/}}
{{- define "observability-dashboards.catalog" -}}
{{- .Files.Get "dashboards/catalog.yaml" | fromYaml | toYaml -}}
{{- end -}}
