apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-grafana.datasourcesName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    {{- include "observability-grafana.datasourcesDoc" . | nindent 4 }}
