"""One-line descriptions for the Kubernetes views' panels, keyed by title.

The upstream set describes only some of its panels; docs/dashboards.md
requires every panel to say what it shows and what to do about it. Applied
by hack/dashboards.py to a panel that has none; upstream's own wording,
where it exists, is kept.

The metric sources are the ones a store holds today: cadvisor and kubelet
(the node scrape) and kube-state-metrics.
"""

DESCRIPTIONS = {
    "Global CPU  Usage": "CPU used across all nodes as a share of their cores, from the root cgroup of each node. Sustained above 70% means the cluster is short of CPU: add nodes or trim requests.",
    "Global RAM Usage": "Memory in use (working set) across all nodes as a share of their RAM. Sustained above 80% means eviction risk: add nodes or find the heavy namespace below.",
    "Nodes": "Nodes registered in the cluster. A drop with no planned scale-down is a node lost: check the Nodes NotReady tile on the Fleet overview.",
    "Kubernetes Resource Count": "How many of each Kubernetes object the cluster holds. Use it to spot a runaway controller creating objects without bound.",
    "Namespaces": "Namespaces in the cluster. An unexpected change is a provisioning or cleanup event worth tracing.",
    "CPU Usage": "CPU cores in use across all nodes. Compare with the cores available above to see the headroom.",
    "RAM Usage": "Memory in use (working set) across all nodes, in bytes. Compare with the RAM available to see the headroom.",
    "Running Pods": "Pods in the Running phase. A sudden drop with no deploy means workloads are being evicted or a node was lost.",
    "Cluster CPU Utilization": "Cluster CPU used as a share of all cores, over time. Read the shape: a plateau near the top is saturation, a spike is a burst.",
    "Cluster Memory Utilization": "Cluster memory in use as a share of all RAM, over time. A steady climb is a leak somewhere: find the namespace in the panels below.",
    "CPU Utilization by namespace": "CPU cores used per namespace. The top line is the heaviest tenant of the cluster; click a series to open that namespace.",
    "Memory Utilization by namespace": "Working-set memory per namespace. The top line is the heaviest tenant; a steady climb is a leak. Click a series to open that namespace.",
    "CPU Utilization by instance": "CPU used per node as a share of its cores. One node far above the rest means uneven scheduling: check for a large pod or missing anti-affinity.",
    "Memory Utilization by instance": "Working-set memory per node. One node near its RAM means eviction risk: look at what runs there.",
    "CPU Throttled seconds by namespace": "Seconds per second that containers were held back by their CPU limit, per namespace. Above zero means limits are too tight: raise the limit or drop it.",
    "Kubernetes Pods QoS classes": "Pods by quality-of-service class. Many BestEffort pods are the first evicted under pressure: give them requests.",
    "Kubernetes Pods Status Reason": "Pods whose status carries a reason (for example Evicted or NodeLost). Anything here is a pod the cluster gave up on: find the reason and its node.",
    "OOM Events by namespace": "Containers killed for exceeding their memory limit, per namespace. Any event means a limit is too low or a leak: raise the limit or fix the leak.",
    "Container Restarts by namespace": "Container restarts per namespace over the interval. A climb is a crash loop or OOM kills: open the namespace, then the pod, and read the last terminated reason.",
    "Network Received by namespace": "Bytes per second received by pods, per namespace. A sudden rise is a traffic spike or a chatty workload.",
    "Namespace(s) usage on total cluster CPU in %": "Share of the whole cluster's CPU the selected namespaces use. High means these namespaces dominate: check their requests against usage.",
    "Namespace(s) usage on total cluster RAM in %": "Share of the whole cluster's memory the selected namespaces use. High means these namespaces dominate the cluster.",
    "Namespace(s) CPU Usage in cores": "CPU cores the selected namespaces use right now.",
    "Namespace(s) RAM Usage in bytes": "Working-set memory the selected namespaces use right now.",
    "CPU usage by Pod": "CPU cores used per pod in the selected namespaces. Click a series to open the pod, and compare with its requests and limits there.",
    "Memory usage by Pod": "Working-set memory per pod in the selected namespaces. A climbing line is a leak; click a series to open the pod.",
    "CPU Throttled seconds by pod": "Seconds per second a pod was held back by its CPU limit. Above zero: raise the limit, or drop it for latency-sensitive work.",
    "OOM Events by namespace, pod": "Containers killed for exceeding their memory limit, per pod. Raise the limit or fix the leak.",
    "Container Restarts by namespace, pod": "Container restarts per pod. Open the pod and read its last terminated reason and exit code.",
    "Nb of pods by state": "Containers by readiness. Not ready for long means a failing probe or a crash: open the pod.",
    "Nb of containers by pod": "Container count per pod. A sudden change is a rollout or a sidecar added or lost.",
    "Replicas available by deployment": "Available replicas per Deployment. Below the desired count means a rollout is stuck or pods cannot start.",
    "Replicas unavailable by deployment": "Unavailable replicas per Deployment. Above zero for long means pods are not starting: open the namespace's failing pods.",
    "Pods with unexpected status": "Pods in a phase other than Running or Succeeded (Pending, Failed, Unknown). Pending for long means it cannot schedule; Failed means it exited: open the pod.",
    "Container Image Used": "Which container images the selected pods run. Use it to confirm a rollout reached every pod.",
    "Persistent Volumes - Capacity and usage in %": "Used space as a share of each volume's capacity. Above 85% expand the claim or clean up before it fills.",
    "Persistent Volumes - Capacity and usage in bytes": "Used and total bytes per volume. Read the growth rate to estimate when it fills.",
    "Persistent Volumes - Inodes": "Used inodes as a share of capacity per volume. Running out of inodes stops writes even with free space: clean up small files.",
    "Network - Bandwidth by pod": "Bytes per second received and sent per pod. A pod far above its peers is the noisy one.",
    "Network - Packets Rate by pod": "Packets per second received and sent per pod. Use it beside bandwidth to tell many small packets from few large ones.",
    "Network - Packets Dropped by pod": "Packets dropped per second per pod. Above zero means saturation or a broken network policy: check the node and the CNI.",
    "Network - Errors by pod": "Network errors per second per pod. Above zero points at a faulty interface or CNI: check the node.",
    "Total pod CPU Requests usage": "Pod CPU use as a share of its CPU requests. Far under 100% means over-requested; far over means the scheduler under-counts this pod.",
    "Total pod CPU Limits usage": "Pod CPU use as a share of its CPU limits. Near 100% means throttling: raise the limit.",
    "Total pod RAM Requests usage": "Pod memory use as a share of its requests. Far over means the scheduler under-counts this pod: raise the request.",
    "Total pod RAM Limits usage": "Pod memory use as a share of its limits. Near 100% means an OOM kill is close: raise the limit or fix the leak.",
    "Resources by container": "Requests, limits and current use per container, side by side. Look for a container with no limit or a limit far from its use.",
    "CPU Usage / Requests & Limits by container": "Container CPU use against its requests and limits. Touching the limit line means throttling.",
    "Memory Usage / Requests & Limits by container": "Container memory working set against its requests and limits. Touching the limit line means an OOM kill is next.",
    "CPU Usage by container": "CPU cores used per container. Find which container in the pod does the work.",
    "Memory Usage by container": "Working-set memory per container. A climbing line is a leak.",
    "CPU Throttled seconds by container": "Seconds per second each container was held back by its CPU limit. Above zero: raise the limit.",
    "OOM Events by container": "Times a container was killed for exceeding its memory limit. Any event: raise the limit or fix the leak.",
    "Container Restarts by container": "Restarts per container. A climb is a crash loop: read the last terminated reason and exit code above.",
    "Pods with Container Issues": "Containers waiting on an error (CrashLoopBackOff, ImagePullBackOff and similar), with the reason. Fix the reason shown: logs for a crash, registry and secret for a pull.",
    "Unscheduled Pods": "Pods the scheduler could not place. Read the pod's events: usually insufficient CPU or memory, or a taint nobody tolerates.",
    "Network - Bandwidth": "Bytes per second received and sent by the pod. A sudden rise is a traffic spike or a retry storm.",
    "Network - Packets Rate": "Packets per second received and sent by the pod.",
    "Network - Packets Dropped": "Packets dropped per second by the pod. Above zero means saturation or a network policy: check the node and the CNI.",
    "Network - Errors": "Network errors per second on the pod's interface. Above zero points at a faulty interface or CNI.",
}
