{{/*
The Alloy configuration, rendered by the SUBCHART (`tpl` on
`alloy.alloy.configMap.content`), from `global.observabilityRum` only.

The shape, per app `<id>`:

  faro.receiver "<id>"                      own port, own key, own origins, own limits
    logs   -> otelcol.receiver.loki "<id>" -> otelcol.processor.transform "<id>_logs"
    traces ->                                 otelcol.processor.transform "<id>_traces"
                                                [-> otelcol.processor.probabilistic_sampler "<id>"]
  then, shared:  memory_limiter -> batch -> otelcol.exporter.otlphttp "gateway"

THE APP IS STAMPED HERE, NEVER READ FROM THE PAYLOAD. Which receiver accepted
a request decides `service.name`, `app` and (when set) the environment: they
are literals in that app's own transform, written as resource attributes
after the payload's own `app_name`/`app_namespace` are deleted, so nothing a
browser sends can say it is a different app.

THE ERROR FINGERPRINT, for every `kind=exception` line, is
  error.fingerprint = first 16 hex of sha256( app | type | message' | frame )
where
  message' = the exception message with, in this order, every URL replaced by
             <url>, every "double" and 'single' quoted string by <str>, every
             UUID by <uuid>, every 0x-prefixed or 8+ digit hex run by <hex>,
             every remaining number by <n>;
  frame    = "<file>:<function>" of the first stack frame that is the app's own
             code, taken from the SYMBOLICATED stack: frames from
             node_modules, browser extensions, anonymous code and other
             origins are skipped, own-origin frames that were never mapped
             keep their script path, and the file loses its query string and
             a bundler's content hash (index-AbC123xy.js -> index.js). Line
             and column are never part of it, so a deploy that only moves
             code does not mint a new issue.
It is a log RECORD attribute, never a resource attribute: the gateway's stream
fields are a short fixed list and a per-error value there would mint a stream
per error. The same message' is stored as `error.message`, the stable title.
See docs/frontend.md.

Raw strings (backticks) everywhere a regular expression appears: the
statements are OpenTelemetry Transformation Language, whose own string
escaping already doubles every backslash, and Alloy's must not double it
again.
*/}}

{{- define "observability-rum.alloyConfig" -}}
{{- include "observability-rum.validate.config" . -}}
{{- $c := .Values.global.observabilityRum -}}
{{- $apps := include "observability-rum.apps" . | fromYamlArray -}}
{{- $privacy := $c.privacy -}}
{{- $smctl := $c.sourcemaps.smctl -}}
{{- $dir := $c.sourcemaps.directory | default "/sourcemaps" -}}
{{- $self := .Values.fullnameOverride | default "observability-rum" -}}
{{- $ns := .Release.Namespace -}}
// Generated by charts/observability-rum. Edit global.observabilityRum, not this.

otelcol.exporter.otlphttp "gateway" {
  client {
    endpoint = {{ $c.otlp.endpoint | quote }}
  }
}

otelcol.processor.batch "default" {
  output {
    logs   = [otelcol.exporter.otlphttp.gateway.input]
    traces = [otelcol.exporter.otlphttp.gateway.input]
  }
}

// Back-pressure for a public endpoint: past the limit the pipeline refuses
// data (the receiver answers an error) instead of the pod being killed.
otelcol.processor.memory_limiter "default" {
  check_interval         = "1s"
  limit_percentage       = 80
  spike_limit_percentage = 25
  output {
    logs   = [otelcol.processor.batch.default.input]
    traces = [otelcol.processor.batch.default.input]
  }
}
{{ range $a := $apps }}
// ---- {{ $a.name }} -------------------------------------------------------

// The app's key, read from its Secret through the API (the chart's Role
// allows `get` on this name only) and re-read every minute, so a rotation
// needs no restart. A missing Secret or key leaves the receiver below
// unstarted: fail closed.
remote.kubernetes.secret "{{ $a.id }}_key" {
  namespace = {{ $ns | quote }}
  name      = {{ $a.secretName | quote }}
}

faro.receiver "{{ $a.id }}" {
  server {
    listen_address           = "0.0.0.0"
    listen_port              = {{ $a.port }}
    cors_allowed_origins     = [{{ range $i, $o := $a.origins }}{{ if $i }}, {{ end }}{{ $o | quote }}{{ end }}]
    api_key                  = remote.kubernetes.secret.{{ $a.id }}_key.data[{{ $a.secretKey | quote }}]
    max_allowed_payload_size = {{ $a.maxPayload | quote }}

    rate_limiting {
      enabled    = true
      strategy   = "global"
      rate       = {{ $a.rate }}
      burst_size = {{ $a.burst }}
    }
  }

  sourcemaps {
    download = false
    cache {
      ttl                    = {{ $c.sourcemaps.cache.ttl | quote }}
      error_cleanup_interval = {{ $c.sourcemaps.cache.missRetry | quote }}
    }
{{- range $p := $a.prefixes }}
    location {
      minified_path_prefix = {{ $p | quote }}
{{- if $smctl.enabled }}
      path                 = "http://{{ $self }}-sourcemaps:8080/{{ $a.name }}/{{ "{{ .Release }}" }}"
{{- else }}
      path                 = "{{ $dir }}/{{ $a.name }}/{{ "{{ .Release }}" }}"
{{- end }}
    }
{{- end }}
  }

  log_format = "json"

  output {
    logs   = [otelcol.receiver.loki.{{ $a.id }}.receiver]
    traces = [otelcol.processor.transform.{{ $a.id }}_traces.input]
  }
}

otelcol.receiver.loki "{{ $a.id }}" {
  output {
    logs = [otelcol.processor.transform.{{ $a.id }}_logs.input]
  }
}

otelcol.processor.transform "{{ $a.id }}_logs" {
  error_mode = "ignore"

  log_statements {
    context = "log"
    statements = [
      // The line is the receiver's JSON; its fields become record attributes.
      `merge_maps(log.attributes, ParseJSON(log.body), "upsert") where IsString(log.body)`,
      // What the payload says about WHICH app it is, is not believed.
      `delete_key(log.attributes, "app_name")`,
      `delete_key(log.attributes, "app_namespace")`,
{{- if $a.environment }}
      `delete_key(log.attributes, "app_environment")`,
{{- end }}
      // Alloy's own `hash` is xxh3 of the unnormalised message: not a grouping key.
      `delete_key(log.attributes, "hash")`,
{{- if $privacy.dropUserAttributes }}
      `delete_matching_keys(log.attributes, "^user_")`,
{{- end }}
{{- if $privacy.stripUrlQueryAndFragment }}
      // ?query and #fragment off every absolute URL in every value; a stack
      // frame's ":line:col)" after the query is kept.
      `replace_all_patterns(log.attributes, "value", "(://[^\\s\"'<>?#]*)[?#][^\\s\"'<>]*?(:[0-9]+:[0-9]+\\)|[\\s\"'<>]|$)", "${1}${2}")`,
{{- end }}
      // ---- error.fingerprint (exceptions only) ----
      // 1. the message, normalised
      `set(log.cache["m"], log.attributes["value"]) where log.attributes["kind"] == "exception"`,
      `replace_pattern(log.cache["m"], "[A-Za-z][A-Za-z0-9+.-]*://[^\\s\"'<>)]*", "<url>")`,
      `replace_pattern(log.cache["m"], "\"[^\"]*\"", "\"<str>\"")`,
      `replace_pattern(log.cache["m"], "'[^']*'", "'<str>'")`,
      `replace_pattern(log.cache["m"], "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}", "<uuid>")`,
      `replace_pattern(log.cache["m"], "\\b0[xX][0-9a-fA-F]+\\b", "<hex>")`,
      `replace_pattern(log.cache["m"], "\\b[0-9a-fA-F]{8,}\\b", "<hex>")`,
      `replace_pattern(log.cache["m"], "\\b[0-9]+(?:\\.[0-9]+)?\\b", "<n>")`,
      // 2. the first frame that is the app's own code
      `set(log.cache["f"], log.attributes["stacktrace"]) where log.attributes["kind"] == "exception"`,
      `replace_pattern(log.cache["f"], "(?:{{ range $i, $o := $a.origins }}{{ if $i }}|{{ end }}{{ regexQuoteMeta $o | replace "\\" "\\\\" }}{{ end }})/", "")`,
      `replace_pattern(log.cache["f"], "\\n  at [^\\n]*(?:node_modules|extension://|<anonymous>|https?://)[^\\n]*", "")`,
      `set(log.cache["top"], ExtractPatterns(log.cache["f"], "\\n  at (?P<fn>[^\\n]*?) \\((?:[^|\\n]*\\|)?(?P<file>[^\\n]*?)(?:\\?[^:\\n]*)?:[0-9]+:[0-9]+\\)")) where log.attributes["kind"] == "exception" and IsMatch(log.cache["f"], "\\n  at ")`,
      `set(log.cache["file"], log.cache["top"]["file"]) where log.cache["top"] != nil`,
      `replace_pattern(log.cache["file"], "[-.][A-Za-z0-9_]{6,16}\\.(m?js)$", ".${1}")`,
      `set(log.attributes["error.frame"], Concat([log.cache["file"], log.cache["top"]["fn"]], ":")) where log.cache["top"] != nil`,
      // 3. the hash
      `set(log.attributes["error.fingerprint"], Substring(SHA256(Concat([{{ $a.name | quote }}, log.attributes["type"], log.cache["m"], log.attributes["error.frame"]], "|")), 0, 16)) where log.attributes["kind"] == "exception"`,
      `set(log.attributes["error.message"], log.cache["m"]) where log.attributes["kind"] == "exception"`,
      // ---- the rest of the record ----
      // Web vitals arrive twice, as `lcp` and as `value_lcp`; keep the latter.
      `delete_matching_keys(log.attributes, "^(cls|fcp|fid|inp|lcp|ttfb)$") where log.attributes["kind"] == "measurement"`,
      // The trace link: structured, so the log store's own correlation works.
      `set(log.trace_id.string, log.attributes["traceID"]) where log.attributes["traceID"] != nil`,
      `set(log.span_id.string, log.attributes["spanID"]) where log.attributes["spanID"] != nil`,
      `delete_key(log.attributes, "traceID")`,
      `delete_key(log.attributes, "spanID")`,
      // The body is the human line, never the raw payload.
      `set(log.body, Concat([log.attributes["type"], log.attributes["value"]], ": ")) where log.attributes["kind"] == "exception"`,
      `set(log.body, log.attributes["message"]) where log.attributes["kind"] == "log"`,
      `set(log.body, Concat([log.attributes["kind"], log.attributes["type"], log.attributes["event_name"]], " ")) where log.attributes["kind"] == "measurement" or log.attributes["kind"] == "event"`,
    ]
  }

  // The identity. Literals of THIS receiver, written last.
  log_statements {
    context = "resource"
    statements = [
      `set(resource.attributes["service.name"], {{ $a.serviceName | quote }})`,
      `set(resource.attributes["app"], {{ $a.name | quote }})`,
      `set(resource.attributes["telemetry.source"], "faro")`,
{{- if $a.environment }}
      `set(resource.attributes["deployment.environment.name"], {{ $a.environment | quote }})`,
{{- end }}
    ]
  }

  output {
    logs = [otelcol.processor.memory_limiter.default.input]
  }
}

otelcol.processor.transform "{{ $a.id }}_traces" {
  error_mode = "ignore"

  trace_statements {
    context = "resource"
    statements = [
      `set(resource.attributes["service.name"], {{ $a.serviceName | quote }})`,
      `set(resource.attributes["app"], {{ $a.name | quote }})`,
      `set(resource.attributes["telemetry.source"], "faro")`,
{{- if $a.environment }}
      `delete_key(resource.attributes, "deployment.environment")`,
      `set(resource.attributes["deployment.environment.name"], {{ $a.environment | quote }})`,
{{- end }}
{{- if $privacy.dropUserAttributes }}
      `delete_matching_keys(resource.attributes, "^(user|enduser)\\.")`,
{{- end }}
    ]
  }

  trace_statements {
    context = "span"
    statements = [
{{- if $privacy.dropUserAttributes }}
      `delete_matching_keys(span.attributes, "^(user|enduser)\\.")`,
{{- end }}
{{- if $privacy.stripUrlQueryAndFragment }}
      `delete_key(span.attributes, "url.query")`,
      `delete_key(span.attributes, "url.fragment")`,
      `replace_pattern(span.attributes["http.target"], "[?#].*$", "") where span.attributes["http.target"] != nil`,
      `replace_all_patterns(span.attributes, "value", "(://[^\\s\"'<>?#]*)[?#][^\\s\"'<>]*?(:[0-9]+:[0-9]+\\)|[\\s\"'<>]|$)", "${1}${2}")`,
{{- end }}
    ]
  }

  output {
{{- if lt (float64 $a.traces) 1.0 }}
    traces = [otelcol.processor.probabilistic_sampler.{{ $a.id }}.input]
{{- else }}
    traces = [otelcol.processor.memory_limiter.default.input]
{{- end }}
  }
}
{{- if lt (float64 $a.traces) 1.0 }}

otelcol.processor.probabilistic_sampler "{{ $a.id }}" {
  sampling_percentage = {{ mulf $a.traces 100.0 }}
  output {
    traces = [otelcol.processor.memory_limiter.default.input]
  }
}
{{- end }}
{{ end -}}
{{- end -}}
